org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
org.gradle.configuration-cache=true

plugin_group=joszza
plugin_name=Music Display
plugin_description=Shows Spotify or Windows system media (YouTube/browser) on a customizable in-game HUD
plugin_author=joszza
plugin_website=https://github.com/jesuisjoszi/MusicDisplay
plugin_main_entrypoint=com.joszza.spotify.SpotifyPlugin
server_version=>=0.5.0-pre.0 <0.6.0
